name: CI
on:
  pull_request:

env:
  FACTORY: andy-corp

jobs:
  build:
    name: Build Yocto
    runs-on: self-hosted
    container:
      image: hub.foundries.io/lmp-sdk
      volumes:
        - /home/doanac/actions-runner/persistent:/persistent
    steps:
      - name: Setup repo
        run: |
          set -ex
          env | sort
          rm -rf repo
          sudo -u builder git clone ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} repo
          cd repo
          sudo -u builder git fetch origin ${GITHUB_REF}:pr
          sudo -u builder git checkout pr
          loc=$(pwd)

          sudo -u builder mkdir /tmp/oe
          cd /tmp/oe
          sudo -u builder repo init -m ${{env.FACTORY}}.xml file://${loc}
          sudo -u builder repo sync

      - name: Set up cache
        run: |
          set -eux
          cd /tmp/oe
          mkdir -p /persistent/sstate-cache /persistent/downloads
          chown builder /persistent/sstate-cache
          chown builder /persistent/downloads
          ln -s /persistent/sstate-cache ./
          ln -s /persistent/downloads ./

      - name: Build Yocto
        run: |
          set -eux
          cd /tmp/oe
          sudo -u builder bash -c "MACHINE=intel-corei7-64 source setup-environment build && bitbake lmp-factory-image"
